version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: itseats
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: idukbaduk
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    networks:
      - local-bridge

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - local-bridge

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - local-bridge

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - local-bridge

  k6:
    image: grafana/k6
    container_name: k6
    stdin_open: true
    tty: true
    volumes:
      - ./scripts:/scripts
    entrypoint: ["sh", "-c"]
    command:
      - |
        echo "⏳ Waiting for Prometheus..."; \
        sleep 5; \
        k6 run --out experimental-prometheus-rw=remoteWriteUrl=http://prometheus:9090/api/v1/write /scripts/healthcheck.js
    depends_on:
      - prometheus
    networks:
      - local-bridge

networks:
  local-bridge:
    driver: bridge
