version: "3.8"

services:
  mysql:
    image: mysql:9.3.0
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: itseats
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: idukbaduk
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    networks:
      - local-bridge

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - local-bridge

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-dashboard:/dashboard
      - ./grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - local-bridge

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - local-bridge

  k6:
    image: grafana/k6
    container_name: k6
    stdin_open: true
    tty: true
    volumes:
      - ./scripts:/scripts
    command: [ "run", "/scripts/healthcheck.js" ]
    environment:
      - K6_OUT=experimental-prometheus-rw
      - K6_PROMETHEUS_RW_SERVER_URL=http://prometheus:9090/api/v1/write
      - K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM=false
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - prometheus
    networks:
      - local-bridge

networks:
  local-bridge:
    driver: bridge
