version: "3.8"

services:
  mysql:
    image: mysql:9.3.0
    container_name: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: itseats
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: idukbaduk
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    networks:
      - local-bridge

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - local-bridge

networks:
  local-bridge:
    driver: bridge
