version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: itseats
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: idukbaduk
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul
    networks:
      - local-bridge

networks:
  local-bridge:
    driver: bridge
