name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
      branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    # Docker Compose 설치 (Ubuntu 22.04에는 기본 포함, 혹시 모르니 명시)
    - name: Set up Docker Compose
      run: sudo apt-get update && sudo apt-get install -y docker-compose

    # docker-compose up (백그라운드로 실행)
    - name: Start docker-compose services
      run: docker-compose -f docker-compose.local.yml up -d

    # MySQL/Redis가 완전히 뜰 때까지 대기 (특히 MySQL은 느릴 수 있음)
    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if docker exec mysql mysqladmin ping -u root -p1234 --silent
            echo "MySQL is up!"
            break
          fi
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Restore application yml files
      run: |
        mkdir -p src/main/resources
        echo "${{ secrets.APP_YML }}" > src/main/resources/application.yml
        echo "${{ secrets.APP_LOCAL_YML }}" > src/main/resources/application-local.yml
        echo "${{ secrets.APP_JWT_YML }}" > src/main/resources/application-jwt.yml
        echo "${{ secrets.APP_OAUTH_YML }}" > src/main/resources/application-oauth.yml

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4 # v4.0.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build --no-daemon

    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    #   with:
    #     gradle-version: '8.9'
    #
    # - name: Build with Gradle 8.9
    #   run: gradle build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
